displayName=Improved Chat TEST
author=wukuna
build=standard
description=Customizable chat overlays, native chat collapse/resize, modern styling, message rules, and alerts.
tags=chat,message,overlay,color,customize,private,clan,rainbow,resize,ui
version=
plugins=com.improvedchat.ImprovedChatPlugin
